#ifndef COLOUR_ID_INCLUDE
#define COLOUR_ID_INCLUDE

enum ColourID {
    COLOUR_ID_NULL,
    COLOUR_ID_EARTH_DAY,
    COLOUR_ID_EARTH_NIGHT,
    COLOUR_ID_TREE,
    COLOUR_ID_HERBIVORE_FEMALE,
    COLOUR_ID_HERBIVORE_MALE,
    COLOUR_ID_N
};

#endif // COLOUR_ID_INCLUDE
